services:
  dancer:
    environment:
      DANCER_CONFIG_OVERLAY_FILE: /run/secrets/dancer_config_overlay
    secrets:
      - dancer_config_overlay

secrets:
  dancer_config_overlay:
    file: ${DANCER_CONFIG_OVERLAY_SOURCE:-./secrets/dancer-config-line}
