foreground = yes
client = yes

[dancer-irc]
accept = 0.0.0.0:6667
connect = \${IRC_TLS_HOST}:\${IRC_TLS_PORT}
verifyChain = yes
checkHost = \${IRC_TLS_HOST}
CApath = /etc/ssl/certs
sni = \${IRC_TLS_HOST}
